### ISSUE TITLE
Encapsula

### ISSUE THREAD

**Issue by lmagarin** [R4f4Lc/Programacion1Daw#1]
https://github.com/R4f4Lc/Programacion1Daw/blob/1d38e98754f2350d20aab08ad54686504943b049/Segundo%20Trimestre/2-%20Segundos%20Ejercicios%20POO/Java/vehiculos/Coche.java#L32

Quizás la marca del coche sólo deba modificarse en el constructor. Entonces debería ser private.

**Comment by R4f4Lc** [comment]
Arreglado!
